"""Command line entry point.

    python src/cli.py                      # run every sample deal
    python src/cli.py --deal DD-1042       # run one
    python src/cli.py --format json        # machine readable
    python src/cli.py --out examples/      # write markdown per deal
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from evaluate import Evaluation, evaluate, load_config
from summarize import summarize

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "sample_deals.json"

DECISION_LABEL = {
    "auto_approve": "AUTO-APPROVED",
    "approval_required": "APPROVAL REQUIRED",
    "blocked": "BLOCKED",
}

SEVERITY_LABEL = {"blocking": "BLOCKING", "review": "REVIEW", "advisory": "ADVISORY"}


def render_markdown(ev: Evaluation, deal: dict, narrative: str) -> str:
    lines = [
        f"# {ev.account_name}: {ev.deal_id}",
        "",
        f"**{DECISION_LABEL[ev.decision]}** | {ev.tier_label} | target turnaround {ev.sla_hours}h",
        "",
        "## Summary",
        "",
        narrative,
        "",
        "## Deal economics",
        "",
        "| | |",
        "|---|---|",
        f"| Deal type | {ev.deal_type.replace('_', ' ')} |",
        f"| Term | {ev.term_months} months |",
        f"| List TCV | ${ev.list_tcv:,.0f} |",
        f"| Net TCV | ${ev.net_tcv:,.0f} |",
        f"| ACV | ${ev.acv:,.0f} |",
        f"| Blended discount | {ev.blended_discount_pct:.1f}% |",
        "",
    ]

    if ev.approvers:
        lines += [
            "## Approvers",
            "",
            *[f"- {a.replace('_', ' ')}" for a in ev.approvers],
            "",
        ]

    if ev.exceptions:
        lines += ["## Exceptions", ""]
        for exc in ev.exceptions:
            reviewers = (
                f" _(routes to: {', '.join(r.replace('_', ' ') for r in exc.reviewers)})_"
                if exc.reviewers
                else ""
            )
            lines.append(f"- **{SEVERITY_LABEL[exc.severity]}**: {exc.message}{reviewers}")
        lines.append("")
    else:
        lines += ["## Exceptions", "", "None. Standard paper, standard terms.", ""]

    lines += ["---", "", "_Synthetic data. Generated by deal-desk-copilot._"]
    return "\n".join(lines)


def render_console(ev: Evaluation, narrative: str) -> str:
    head = f"{ev.deal_id}  {ev.account_name}"
    bar = "=" * max(len(head), 56)
    out = [
        bar,
        head,
        bar,
        f"{DECISION_LABEL[ev.decision]}  |  {ev.tier_label}  |  SLA {ev.sla_hours}h",
        f"Net TCV ${ev.net_tcv:,.0f}  |  ACV ${ev.acv:,.0f}  |  "
        f"discount {ev.blended_discount_pct:.1f}%  |  {ev.term_months}mo",
        "",
        narrative,
    ]
    if ev.exceptions:
        out += ["", "Exceptions:"]
        for exc in ev.exceptions:
            out.append(f"  [{SEVERITY_LABEL[exc.severity]:>8}] {exc.message}")
    if ev.approvers:
        out += ["", "Approvers: " + ", ".join(a.replace("_", " ") for a in ev.approvers)]
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate deals against desk policy.")
    parser.add_argument("--deal", help="Evaluate a single deal by id")
    parser.add_argument("--format", choices=["console", "json", "markdown"], default="console")
    parser.add_argument("--out", help="Directory to write one markdown file per deal")
    parser.add_argument("--data", default=str(DATA), help="Path to deals JSON")
    args = parser.parse_args()

    with open(args.data) as f:
        deals = json.load(f)

    if args.deal:
        deals = [d for d in deals if d["deal_id"] == args.deal]
        if not deals:
            raise SystemExit(f"No deal with id {args.deal}")

    matrix, pricing = load_config()
    results = []

    for deal in deals:
        ev = evaluate(deal, matrix, pricing)
        narrative = summarize(ev, deal)
        results.append((deal, ev, narrative))

    if args.out:
        outdir = Path(args.out)
        outdir.mkdir(parents=True, exist_ok=True)
        for deal, ev, narrative in results:
            slug = deal.get("slug") or ev.deal_id.lower()
            path = outdir / f"output_{slug}.md"
            path.write_text(render_markdown(ev, deal, narrative))
            print(f"wrote {path}")
        return

    if args.format == "json":
        payload = [
            {**ev.to_dict(), "summary": narrative} for _, ev, narrative in results
        ]
        print(json.dumps(payload, indent=2))
        return

    if args.format == "markdown":
        for deal, ev, narrative in results:
            print(render_markdown(ev, deal, narrative))
            print()
        return

    for _, ev, narrative in results:
        print(render_console(ev, narrative))


if __name__ == "__main__":
    main()
